pipeline {
  agent {
    label 'linux'
  }

  parameters {
    string(name: 'buildVersion',  description: 'Build version', defaultValue: '1.0.${BUILD_NUMBER}')
  }

  environment {
     DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
     FN_API_URL = credentials('FN_API_URL')
  }

  stages {
      stage('Build & Deploy') {
        steps {
          sh "cd fn-cors-proxy && ./gradlew fnDeploy -PBUILD_VERSION=${params.buildVersion} -PDOCKER_REGISTRY=${credentials('DOCKER_REGISTRY')} -PFN_API_URL=${credentials('FN_API_URL')}"
        }
      }
      stage('Cleanup') {
        steps {
          sh "cd fn-cors-proxy && ./gradlew clean"
        }
      }
  }
}